// steps 1-2 are hand-curated (tools/selections_12.js); step 3 is generated by tools/step3.js (selections3.json);
// extras (tools/extras.js): per-game attachments + standalone minigame / cheat-device cards.
const fs=require('fs'),path=require('path');
const rd=f=>{const p=path.join(__dirname,f);return fs.existsSync(p)?require(p):null;};
const attach=rd('extras_attach.json')||{};
const games=[...require('./tools/selections_12'),...(rd('selections3.json')||[])].map(s=>attach[s.dir]?{...s,extras:attach[s.dir]}:s);
module.exports=[...games,...(rd('selections_extras.json')||[])];
