// steps 1-2 are hand-curated (tools/selections_12.js); step 3 is generated by tools/step3.js (selections3.json)
const fs=require('fs'),path=require('path');
const p=path.join(__dirname,'selections3.json');
module.exports=[...require('./tools/selections_12'),...(fs.existsSync(p)?require(p):[])];
