// steps 1-2 are hand-curated (tools/selections_12.js); step 3 is generated by tools/step3.js (selections3.json);
// extras (tools/extras.js): per-game attachments + standalone minigame / cheat-device cards.
// Card folder IDs: the VMU Pro GameID is the disc-header Product Number (e.g. MK-51000), NOT the Redump serial (51000),
// so ids are remapped here via gameid.json (from kevh182/Redump_GameID) using the Redump entries behind each selection.
const fs=require('fs'),path=require('path');
const rd=f=>{const p=path.join(__dirname,f);return fs.existsSync(p)?require(p):null;};
const {lookup}=require('./tools/gameid_lookup');
const dat=require('./redump.json');
const EXCL=/\((Demo|Beta|Proto|Taikenban|Tentou|Kiosk|Preview|Sample|Trial|Video ROM|Tentou-you)/i;
const regOf=r=>({US:/\((USA|Canada)/,EU:/\((Europe|UK)\)/,JP:/\(Japan/}[r]);
function remap(s){
  let ents=[];
  if(s.rname&&!/^\(/.test(s.rname)){const names=new Set(s.rname.split(' | '));ents=dat.filter(e=>names.has(e.name));}
  if(!ents.length){const re=regOf(s.region);ents=dat.filter(e=>!EXCL.test(e.name)&&(!re||re.test(e.name))&&s.ids.some(i=>e.serial.split(/,\s*/).includes(i)));}
  const pn=[...new Set(ents.map(lookup).filter(Boolean).map(x=>x.replace(/ 00$/,'').replace(/[-\s]/g,'')))];
  if(!pn.length)return s;
  const old=s.ids.map(i=>i.replace(/[-\s]/g,''));
  // header numbers that are placeholders/ambiguous (T0000M is shared by homebrew) also keep the Redump-serial folder
  const ids=pn.some(x=>/^T0000|^\d/.test(x))?[...new Set([...pn,...old])]:pn;
  return {...s,ids:[...new Set([...ids,...(ALIAS[s.dir]||[])])],oldIds:s.ids};
}
const attach=rd('extras_attach.json')||{};
const disc0=rd('selections_disc.json')||{upgrades:{},new:[]};
const keep=x=>!(process.env.NO_BLUESWIRL&&x.restricted==='blueswirl'); // NO_BLUESWIRL=1 drops Blue Swirl-derived picks (easy revert)
const disc={upgrades:Object.fromEntries(Object.entries(disc0.upgrades).filter(([k,v])=>keep(v))),new:disc0.new.filter(keep)};
const upgrade=s=>{const u=disc.upgrades[s.dir];if(!u)return s;const att=(s.extras||[]).filter(e=>!(u.drop||[]).includes(e));return {...s,srcdir:u.srcdir,files:u.files,status:u.status,notes:u.notes,completion:'Upgraded from the VMU Tool Dream Explorer disc: '+u.notes,extras:[]};};
const ALIAS={nightcreature2:['T9504N']}; // header number per kevh182 list differs from K3zter's DB: keep both
const games=[...require('./tools/selections_12'),...require('./tools/selections_fix'),...(rd('selections3.json')||[]),...disc.new].map(s=>attach[s.dir]?{...s,extras:attach[s.dir]}:s).map(upgrade).map(remap);
module.exports=[...games,...(rd('selections_extras.json')||[]).filter(keep)];
